name: Deploy Components to Mainnet
on:
  push:
    branches: [main]
jobs:
  deploy-mainnet:
    uses: FroVolod/bos-cli-rs/.github/workflows/deploy-mainnet.yml@main
    with:
      deploy-account-address: bos-dev.near
      signer-account-address: bos-dev.near
      signer-public-key: ed25519:Ak33GAqJzoR8Pq2YxVwtiPofNtsZhdQqSMNqc6DMxpg2
    secrets:
      SIGNER_PRIVATE_KEY: ${{ secrets.SIGNER_PRIVATE_KEY }}