name: Deploy Components to Mainnet
on:
  push:
    branches: [main]
jobs:
  deploy-mainnet:
    uses: FroVolod/bos-cli-rs/.github/workflows/deploy-mainnet.yml@main
    with:
      deploy-account-address: <FILL>
      signer-account-address: <FILL>
      signer-public-key: <FILL>
    secrets:
      SIGNER_PRIVATE_KEY: ${{ secrets.SIGNER_PRIVATE_KEY }}